# Generated by Django 6.0.5 on 2026-06-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adspace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='adspaces/'),
        ),
    ]
